[workspace]
resolver = "2"
members = [
    "TUI/universe_manager",
    "TUI/filen_tui",
    "TUI/opencode_manager",
    "TUI/img_splt",
    "TUI/universal_converter",
    "GUI/universe_manager_gui",
    "GUI/filen_gui",
    "GUI/opencode_manager_gui",
    "GUI/img_splt_gui",
    "GUI/universal_converter_gui",
    "GUI/subscription_manager_gui/backend",
    "GUI/rclone_gui/backend",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort"
strip = true
